<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2018-04-19 02:38:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\BookclubDiscuss
 *
 * @ORM\Entity(repositoryClass="BookclubDiscussRepository")
 * @ORM\Table(name="bookclub_discuss", indexes={@ORM\Index(name="fk_bookclub_discuss_user1_idx", columns={"user_id"})})
 */
class BookclubDiscuss implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $is_autosave;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $lastupdate;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $title;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $content;

    /**
     * @ORM\Column(type="integer")
     */
    protected $user_id;

    /**
     * @ORM\OneToOne(targetEntity="Bookclub", mappedBy="bookclubDiscuss")
     */
    protected $bookclub;

    /**
     * @ORM\OneToMany(targetEntity="BookclubComment", mappedBy="bookclubDiscuss")
     * @ORM\JoinColumn(name="id", referencedColumnName="bookclub_discuss_id", nullable=false)
     */
    protected $bookclubComments;

    /**
     * @ORM\OneToOne(targetEntity="User", inversedBy="bookclubDiscuss")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    protected $user;

    public function __construct()
    {
        $this->bookclubs = new ArrayCollection();
        $this->bookclubComments = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\BookclubDiscuss
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of is_autosave.
     *
     * @param boolean $is_autosave
     * @return \Base\Entity\BookclubDiscuss
     */
    public function setIsAutosave($is_autosave)
    {
        $this->is_autosave = $is_autosave;

        return $this;
    }

    /**
     * Get the value of is_autosave.
     *
     * @return boolean
     */
    public function getIsAutosave()
    {
        return $this->is_autosave;
    }

    /**
     * Set the value of lastupdate.
     *
     * @param \DateTime $lastupdate
     * @return \Base\Entity\BookclubDiscuss
     */
    public function setLastupdate($lastupdate)
    {
        $this->lastupdate = $lastupdate;

        return $this;
    }

    /**
     * Get the value of lastupdate.
     *
     * @return \DateTime
     */
    public function getLastupdate()
    {
        return $this->lastupdate;
    }

    /**
     * Set the value of title.
     *
     * @param string $title
     * @return \Base\Entity\BookclubDiscuss
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get the value of title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set the value of content.
     *
     * @param string $content
     * @return \Base\Entity\BookclubDiscuss
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get the value of content.
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set the value of user_id.
     *
     * @param integer $user_id
     * @return \Base\Entity\BookclubDiscuss
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Get the value of user_id.
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Set Bookclub entity (one to one).
     *
     * @param \Base\Entity\Bookclub $bookclub
     * @return \Base\Entity\BookclubDiscuss
     */
    public function setBookclub(Bookclub $bookclub = null)
    {
        $bookclub->setBookclubDiscuss($this);
        $this->bookclub = $bookclub;

        return $this;
    }

    /**
     * Get Bookclub entity (one to one).
     *
     * @return \Base\Entity\Bookclub
     */
    public function getBookclub()
    {
        return $this->bookclub;
    }

    /**
     * Add BookclubComment entity to collection (one to many).
     *
     * @param \Base\Entity\BookclubComment $bookclubComment
     * @return \Base\Entity\BookclubDiscuss
     */
    public function addBookclubComment(BookclubComment $bookclubComment)
    {
        $this->bookclubComments[] = $bookclubComment;

        return $this;
    }

    /**
     * Remove BookclubComment entity from collection (one to many).
     *
     * @param \Base\Entity\BookclubComment $bookclubComment
     * @return \Base\Entity\BookclubDiscuss
     */
    public function removeBookclubComment(BookclubComment $bookclubComment)
    {
        $this->bookclubComments->removeElement($bookclubComment);

        return $this;
    }

    /**
     * Get BookclubComment entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBookclubComments()
    {
        return $this->bookclubComments;
    }

    /**
     * Set User entity (one to one).
     *
     * @param \Base\Entity\User $user
     * @return \Base\Entity\BookclubDiscuss
     */
    public function setUser(User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get User entity (one to one).
     *
     * @return \Base\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'is_autosave',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'lastupdate',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'title',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'content',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'user_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'is_autosave', 'lastupdate', 'title', 'content', 'user_id');
        $relationFields = array('user');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'is_autosave', 'lastupdate', 'title', 'content', 'user_id');
    }
}