<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2018-04-19 02:38:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\BookHasReadingCertificate
 *
 * @ORM\Entity(repositoryClass="BookHasReadingCertificateRepository")
 * @ORM\Table(name="book_has_reading_certificate", indexes={@ORM\Index(name="fk_book_has_reading_certificate_reading_certificate1_idx", columns={"reading_certificate_id"}), @ORM\Index(name="fk_book_has_reading_certificate_book1_idx", columns={"book_id"})})
 */
class BookHasReadingCertificate implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $book_id;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $reading_certificate_id;

    /**
     * @ORM\ManyToOne(targetEntity="Book", inversedBy="bookHasReadingCertificates")
     * @ORM\JoinColumn(name="book_id", referencedColumnName="id", nullable=false)
     */
    protected $book;

    /**
     * @ORM\ManyToOne(targetEntity="ReadingCertificate", inversedBy="bookHasReadingCertificates")
     * @ORM\JoinColumn(name="reading_certificate_id", referencedColumnName="id", nullable=false)
     */
    protected $readingCertificate;

    public function __construct()
    {
    }

    /**
     * Set the value of book_id.
     *
     * @param integer $book_id
     * @return \Base\Entity\BookHasReadingCertificate
     */
    public function setBookId($book_id)
    {
        $this->book_id = $book_id;

        return $this;
    }

    /**
     * Get the value of book_id.
     *
     * @return integer
     */
    public function getBookId()
    {
        return $this->book_id;
    }

    /**
     * Set the value of reading_certificate_id.
     *
     * @param integer $reading_certificate_id
     * @return \Base\Entity\BookHasReadingCertificate
     */
    public function setReadingCertificateId($reading_certificate_id)
    {
        $this->reading_certificate_id = $reading_certificate_id;

        return $this;
    }

    /**
     * Get the value of reading_certificate_id.
     *
     * @return integer
     */
    public function getReadingCertificateId()
    {
        return $this->reading_certificate_id;
    }

    /**
     * Set Book entity (many to one).
     *
     * @param \Base\Entity\Book $book
     * @return \Base\Entity\BookHasReadingCertificate
     */
    public function setBook(Book $book = null)
    {
        $this->book = $book;

        return $this;
    }

    /**
     * Get Book entity (many to one).
     *
     * @return \Base\Entity\Book
     */
    public function getBook()
    {
        return $this->book;
    }

    /**
     * Set ReadingCertificate entity (many to one).
     *
     * @param \Base\Entity\ReadingCertificate $readingCertificate
     * @return \Base\Entity\BookHasReadingCertificate
     */
    public function setReadingCertificate(ReadingCertificate $readingCertificate = null)
    {
        $this->readingCertificate = $readingCertificate;

        return $this;
    }

    /**
     * Get ReadingCertificate entity (many to one).
     *
     * @return \Base\Entity\ReadingCertificate
     */
    public function getReadingCertificate()
    {
        return $this->readingCertificate;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'book_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'reading_certificate_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('book_id', 'reading_certificate_id');
        $relationFields = array('book', 'readingCertificate');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('book_id', 'reading_certificate_id');
    }
}