<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2018-04-19 02:38:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\PageHasPageTag
 *
 * @ORM\Entity(repositoryClass="PageHasPageTagRepository")
 * @ORM\Table(name="page_has_page_tag", indexes={@ORM\Index(name="IDX_604CE968C4663E4", columns={"page_id"}), @ORM\Index(name="IDX_604CE968D504950F", columns={"page_tag_id"})})
 */
class PageHasPageTag implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $page_id;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $page_tag_id;

    /**
     * @ORM\ManyToOne(targetEntity="Page", inversedBy="pageHasPageTags")
     * @ORM\JoinColumn(name="page_id", referencedColumnName="id", nullable=false)
     */
    protected $page;

    /**
     * @ORM\ManyToOne(targetEntity="PageTag", inversedBy="pageHasPageTags")
     * @ORM\JoinColumn(name="page_tag_id", referencedColumnName="id", nullable=false)
     */
    protected $pageTag;

    public function __construct()
    {
    }

    /**
     * Set the value of page_id.
     *
     * @param integer $page_id
     * @return \Base\Entity\PageHasPageTag
     */
    public function setPageId($page_id)
    {
        $this->page_id = $page_id;

        return $this;
    }

    /**
     * Get the value of page_id.
     *
     * @return integer
     */
    public function getPageId()
    {
        return $this->page_id;
    }

    /**
     * Set the value of page_tag_id.
     *
     * @param integer $page_tag_id
     * @return \Base\Entity\PageHasPageTag
     */
    public function setPageTagId($page_tag_id)
    {
        $this->page_tag_id = $page_tag_id;

        return $this;
    }

    /**
     * Get the value of page_tag_id.
     *
     * @return integer
     */
    public function getPageTagId()
    {
        return $this->page_tag_id;
    }

    /**
     * Set Page entity (many to one).
     *
     * @param \Base\Entity\Page $page
     * @return \Base\Entity\PageHasPageTag
     */
    public function setPage(Page $page = null)
    {
        $this->page = $page;

        return $this;
    }

    /**
     * Get Page entity (many to one).
     *
     * @return \Base\Entity\Page
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Set PageTag entity (many to one).
     *
     * @param \Base\Entity\PageTag $pageTag
     * @return \Base\Entity\PageHasPageTag
     */
    public function setPageTag(PageTag $pageTag = null)
    {
        $this->pageTag = $pageTag;

        return $this;
    }

    /**
     * Get PageTag entity (many to one).
     *
     * @return \Base\Entity\PageTag
     */
    public function getPageTag()
    {
        return $this->pageTag;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'page_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'page_tag_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('page_id', 'page_tag_id');
        $relationFields = array('page', 'pageTag');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('page_id', 'page_tag_id');
    }
}