<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2018-04-19 02:38:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\ReadingCertificate
 *
 * @ORM\Entity(repositoryClass="ReadingCertificateRepository")
 * @ORM\Table(name="reading_certificate")
 */
class ReadingCertificate implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    protected $question;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $option1;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $option2;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $option3;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $option4;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    protected $answer;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $click;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $student_level;

    /**
     * @ORM\OneToMany(targetEntity="BookHasReadingCertificate", mappedBy="readingCertificate")
     * @ORM\JoinColumn(name="id", referencedColumnName="reading_certificate_id", nullable=false)
     */
    protected $bookHasReadingCertificates;

    /**
     * @ORM\OneToMany(targetEntity="StudentHasReadingCertificate", mappedBy="readingCertificate")
     * @ORM\JoinColumn(name="id", referencedColumnName="reading_certificate_id", nullable=false)
     */
    protected $studentHasReadingCertificates;

    /**
     * @ORM\OneToMany(targetEntity="TeacherHasReadingCertificate", mappedBy="readingCertificate")
     * @ORM\JoinColumn(name="id", referencedColumnName="reading_certificate_id", nullable=false)
     */
    protected $teacherHasReadingCertificates;

    public function __construct()
    {
        $this->bookHasReadingCertificates = new ArrayCollection();
        $this->studentHasReadingCertificates = new ArrayCollection();
        $this->teacherHasReadingCertificates = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\ReadingCertificate
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of question.
     *
     * @param string $question
     * @return \Base\Entity\ReadingCertificate
     */
    public function setQuestion($question)
    {
        $this->question = $question;

        return $this;
    }

    /**
     * Get the value of question.
     *
     * @return string
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * Set the value of option1.
     *
     * @param string $option1
     * @return \Base\Entity\ReadingCertificate
     */
    public function setOption1($option1)
    {
        $this->option1 = $option1;

        return $this;
    }

    /**
     * Get the value of option1.
     *
     * @return string
     */
    public function getOption1()
    {
        return $this->option1;
    }

    /**
     * Set the value of option2.
     *
     * @param string $option2
     * @return \Base\Entity\ReadingCertificate
     */
    public function setOption2($option2)
    {
        $this->option2 = $option2;

        return $this;
    }

    /**
     * Get the value of option2.
     *
     * @return string
     */
    public function getOption2()
    {
        return $this->option2;
    }

    /**
     * Set the value of option3.
     *
     * @param string $option3
     * @return \Base\Entity\ReadingCertificate
     */
    public function setOption3($option3)
    {
        $this->option3 = $option3;

        return $this;
    }

    /**
     * Get the value of option3.
     *
     * @return string
     */
    public function getOption3()
    {
        return $this->option3;
    }

    /**
     * Set the value of option4.
     *
     * @param string $option4
     * @return \Base\Entity\ReadingCertificate
     */
    public function setOption4($option4)
    {
        $this->option4 = $option4;

        return $this;
    }

    /**
     * Get the value of option4.
     *
     * @return string
     */
    public function getOption4()
    {
        return $this->option4;
    }

    /**
     * Set the value of answer.
     *
     * @param string $answer
     * @return \Base\Entity\ReadingCertificate
     */
    public function setAnswer($answer)
    {
        $this->answer = $answer;

        return $this;
    }

    /**
     * Get the value of answer.
     *
     * @return string
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    /**
     * Set the value of click.
     *
     * @param integer $click
     * @return \Base\Entity\ReadingCertificate
     */
    public function setClick($click)
    {
        $this->click = $click;

        return $this;
    }

    /**
     * Get the value of click.
     *
     * @return integer
     */
    public function getClick()
    {
        return $this->click;
    }

    /**
     * Set the value of student_level.
     *
     * @param string $student_level
     * @return \Base\Entity\ReadingCertificate
     */
    public function setStudentLevel($student_level)
    {
        $this->student_level = $student_level;

        return $this;
    }

    /**
     * Get the value of student_level.
     *
     * @return string
     */
    public function getStudentLevel()
    {
        return $this->student_level;
    }

    /**
     * Add BookHasReadingCertificate entity to collection (one to many).
     *
     * @param \Base\Entity\BookHasReadingCertificate $bookHasReadingCertificate
     * @return \Base\Entity\ReadingCertificate
     */
    public function addBookHasReadingCertificate(BookHasReadingCertificate $bookHasReadingCertificate)
    {
        $this->bookHasReadingCertificates[] = $bookHasReadingCertificate;

        return $this;
    }

    /**
     * Remove BookHasReadingCertificate entity from collection (one to many).
     *
     * @param \Base\Entity\BookHasReadingCertificate $bookHasReadingCertificate
     * @return \Base\Entity\ReadingCertificate
     */
    public function removeBookHasReadingCertificate(BookHasReadingCertificate $bookHasReadingCertificate)
    {
        $this->bookHasReadingCertificates->removeElement($bookHasReadingCertificate);

        return $this;
    }

    /**
     * Get BookHasReadingCertificate entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBookHasReadingCertificates()
    {
        return $this->bookHasReadingCertificates;
    }

    /**
     * Add StudentHasReadingCertificate entity to collection (one to many).
     *
     * @param \Base\Entity\StudentHasReadingCertificate $studentHasReadingCertificate
     * @return \Base\Entity\ReadingCertificate
     */
    public function addStudentHasReadingCertificate(StudentHasReadingCertificate $studentHasReadingCertificate)
    {
        $this->studentHasReadingCertificates[] = $studentHasReadingCertificate;

        return $this;
    }

    /**
     * Remove StudentHasReadingCertificate entity from collection (one to many).
     *
     * @param \Base\Entity\StudentHasReadingCertificate $studentHasReadingCertificate
     * @return \Base\Entity\ReadingCertificate
     */
    public function removeStudentHasReadingCertificate(StudentHasReadingCertificate $studentHasReadingCertificate)
    {
        $this->studentHasReadingCertificates->removeElement($studentHasReadingCertificate);

        return $this;
    }

    /**
     * Get StudentHasReadingCertificate entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStudentHasReadingCertificates()
    {
        return $this->studentHasReadingCertificates;
    }

    /**
     * Add TeacherHasReadingCertificate entity to collection (one to many).
     *
     * @param \Base\Entity\TeacherHasReadingCertificate $teacherHasReadingCertificate
     * @return \Base\Entity\ReadingCertificate
     */
    public function addTeacherHasReadingCertificate(TeacherHasReadingCertificate $teacherHasReadingCertificate)
    {
        $this->teacherHasReadingCertificates[] = $teacherHasReadingCertificate;

        return $this;
    }

    /**
     * Remove TeacherHasReadingCertificate entity from collection (one to many).
     *
     * @param \Base\Entity\TeacherHasReadingCertificate $teacherHasReadingCertificate
     * @return \Base\Entity\ReadingCertificate
     */
    public function removeTeacherHasReadingCertificate(TeacherHasReadingCertificate $teacherHasReadingCertificate)
    {
        $this->teacherHasReadingCertificates->removeElement($teacherHasReadingCertificate);

        return $this;
    }

    /**
     * Get TeacherHasReadingCertificate entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTeacherHasReadingCertificates()
    {
        return $this->teacherHasReadingCertificates;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'question',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'option1',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'option2',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'option3',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'option4',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'answer',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'click',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'student_level',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'question', 'option1', 'option2', 'option3', 'option4', 'answer', 'click', 'student_level');
        $relationFields = array();
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'question', 'option1', 'option2', 'option3', 'option4', 'answer', 'click', 'student_level');
    }
}