<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2018-04-19 02:38:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\SchoolExt
 *
 * @ORM\Entity(repositoryClass="SchoolExtRepository")
 * @ORM\Table(name="school_ext", indexes={@ORM\Index(name="fk_location_school1_idx", columns={"school_id"})})
 */
class SchoolExt implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $school_id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $city;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $town;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $road;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $adddress_detail;

    /**
     * @ORM\ManyToOne(targetEntity="School", inversedBy="schoolExts")
     * @ORM\JoinColumn(name="school_id", referencedColumnName="id", nullable=false)
     */
    protected $school;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\SchoolExt
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of school_id.
     *
     * @param integer $school_id
     * @return \Base\Entity\SchoolExt
     */
    public function setSchoolId($school_id)
    {
        $this->school_id = $school_id;

        return $this;
    }

    /**
     * Get the value of school_id.
     *
     * @return integer
     */
    public function getSchoolId()
    {
        return $this->school_id;
    }

    /**
     * Set the value of city.
     *
     * @param string $city
     * @return \Base\Entity\SchoolExt
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get the value of city.
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set the value of town.
     *
     * @param string $town
     * @return \Base\Entity\SchoolExt
     */
    public function setTown($town)
    {
        $this->town = $town;

        return $this;
    }

    /**
     * Get the value of town.
     *
     * @return string
     */
    public function getTown()
    {
        return $this->town;
    }

    /**
     * Set the value of road.
     *
     * @param string $road
     * @return \Base\Entity\SchoolExt
     */
    public function setRoad($road)
    {
        $this->road = $road;

        return $this;
    }

    /**
     * Get the value of road.
     *
     * @return string
     */
    public function getRoad()
    {
        return $this->road;
    }

    /**
     * Set the value of adddress_detail.
     *
     * @param string $adddress_detail
     * @return \Base\Entity\SchoolExt
     */
    public function setAdddressDetail($adddress_detail)
    {
        $this->adddress_detail = $adddress_detail;

        return $this;
    }

    /**
     * Get the value of adddress_detail.
     *
     * @return string
     */
    public function getAdddressDetail()
    {
        return $this->adddress_detail;
    }

    /**
     * Set School entity (many to one).
     *
     * @param \Base\Entity\School $school
     * @return \Base\Entity\SchoolExt
     */
    public function setSchool(School $school = null)
    {
        $this->school = $school;

        return $this;
    }

    /**
     * Get School entity (many to one).
     *
     * @return \Base\Entity\School
     */
    public function getSchool()
    {
        return $this->school;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'school_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'city',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'town',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'road',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'adddress_detail',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'school_id', 'city', 'town', 'road', 'adddress_detail');
        $relationFields = array('school');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'school_id', 'city', 'town', 'road', 'adddress_detail');
    }
}