<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2018-04-19 02:38:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\StudentHasReadingCertificate
 *
 * @ORM\Entity(repositoryClass="StudentHasReadingCertificateRepository")
 * @ORM\Table(name="student_has_reading_certificate", indexes={@ORM\Index(name="fk_student_has_reading_certificate_reading_certificate1_idx", columns={"reading_certificate_id"}), @ORM\Index(name="fk_student_has_reading_certificate_student1_idx", columns={"student_id"})})
 */
class StudentHasReadingCertificate implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $student_id;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    protected $reading_certificate_id;

    /**
     * @ORM\Column(name="`type`", type="boolean", nullable=true)
     */
    protected $type;

    /**
     * 認証日期 or 校正舉報 日期
     *
     * @ORM\Column(name="`date`", type="datetime", nullable=true)
     */
    protected $date;

    /**
     * 答對題數
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $correct;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $is_passed;

    /**
     * 閱讀認証是否停權
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $has_right;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $available_time;

    /**
     * @ORM\ManyToOne(targetEntity="Student", inversedBy="studentHasReadingCertificates")
     * @ORM\JoinColumn(name="student_id", referencedColumnName="id", nullable=false)
     */
    protected $student;

    /**
     * @ORM\ManyToOne(targetEntity="ReadingCertificate", inversedBy="studentHasReadingCertificates")
     * @ORM\JoinColumn(name="reading_certificate_id", referencedColumnName="id", nullable=false)
     */
    protected $readingCertificate;

    public function __construct()
    {
    }

    /**
     * Set the value of student_id.
     *
     * @param integer $student_id
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setStudentId($student_id)
    {
        $this->student_id = $student_id;

        return $this;
    }

    /**
     * Get the value of student_id.
     *
     * @return integer
     */
    public function getStudentId()
    {
        return $this->student_id;
    }

    /**
     * Set the value of reading_certificate_id.
     *
     * @param integer $reading_certificate_id
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setReadingCertificateId($reading_certificate_id)
    {
        $this->reading_certificate_id = $reading_certificate_id;

        return $this;
    }

    /**
     * Get the value of reading_certificate_id.
     *
     * @return integer
     */
    public function getReadingCertificateId()
    {
        return $this->reading_certificate_id;
    }

    /**
     * Set the value of type.
     *
     * @param boolean $type
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get the value of type.
     *
     * @return boolean
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set the value of date.
     *
     * @param \DateTime $date
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get the value of date.
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set the value of correct.
     *
     * @param integer $correct
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setCorrect($correct)
    {
        $this->correct = $correct;

        return $this;
    }

    /**
     * Get the value of correct.
     *
     * @return integer
     */
    public function getCorrect()
    {
        return $this->correct;
    }

    /**
     * Set the value of is_passed.
     *
     * @param boolean $is_passed
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setIsPassed($is_passed)
    {
        $this->is_passed = $is_passed;

        return $this;
    }

    /**
     * Get the value of is_passed.
     *
     * @return boolean
     */
    public function getIsPassed()
    {
        return $this->is_passed;
    }

    /**
     * Set the value of has_right.
     *
     * @param boolean $has_right
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setHasRight($has_right)
    {
        $this->has_right = $has_right;

        return $this;
    }

    /**
     * Get the value of has_right.
     *
     * @return boolean
     */
    public function getHasRight()
    {
        return $this->has_right;
    }

    /**
     * Set the value of available_time.
     *
     * @param \DateTime $available_time
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setAvailableTime($available_time)
    {
        $this->available_time = $available_time;

        return $this;
    }

    /**
     * Get the value of available_time.
     *
     * @return \DateTime
     */
    public function getAvailableTime()
    {
        return $this->available_time;
    }

    /**
     * Set Student entity (many to one).
     *
     * @param \Base\Entity\Student $student
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setStudent(Student $student = null)
    {
        $this->student = $student;

        return $this;
    }

    /**
     * Get Student entity (many to one).
     *
     * @return \Base\Entity\Student
     */
    public function getStudent()
    {
        return $this->student;
    }

    /**
     * Set ReadingCertificate entity (many to one).
     *
     * @param \Base\Entity\ReadingCertificate $readingCertificate
     * @return \Base\Entity\StudentHasReadingCertificate
     */
    public function setReadingCertificate(ReadingCertificate $readingCertificate = null)
    {
        $this->readingCertificate = $readingCertificate;

        return $this;
    }

    /**
     * Get ReadingCertificate entity (many to one).
     *
     * @return \Base\Entity\ReadingCertificate
     */
    public function getReadingCertificate()
    {
        return $this->readingCertificate;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'student_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'reading_certificate_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'type',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'date',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'correct',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'is_passed',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'has_right',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'available_time',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('student_id', 'reading_certificate_id', 'type', 'date', 'correct', 'is_passed', 'has_right', 'available_time');
        $relationFields = array('student', 'readingCertificate');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('student_id', 'reading_certificate_id', 'type', 'date', 'correct', 'is_passed', 'has_right', 'available_time');
    }
}