<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2018-04-19 02:38:07.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\Teacher
 *
 * @ORM\Entity(repositoryClass="TeacherRepository")
 * @ORM\Table(name="teacher", indexes={@ORM\Index(name="fk_teacher_user1_idx1", columns={"user_id"})})
 */
class Teacher implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $user_id;

    /**
     * @ORM\Column(name="`name`", type="string", length=45)
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=65)
     */
    protected $edu_key;

    /**
     * @ORM\Column(type="string", length=6, nullable=true)
     */
    protected $gender;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $last_update;

    /**
     * @ORM\OneToMany(targetEntity="SemesterTeacher", mappedBy="teacher")
     * @ORM\JoinColumn(name="id", referencedColumnName="teacher_id", nullable=false)
     */
    protected $semesterTeachers;

    /**
     * @ORM\OneToMany(targetEntity="TeacherHasReadingCertificate", mappedBy="teacher")
     * @ORM\JoinColumn(name="id", referencedColumnName="teacher_id", nullable=false)
     */
    protected $teacherHasReadingCertificates;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="teachers")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    protected $user;

    /**
     * @ORM\ManyToMany(targetEntity="School", mappedBy="teachers")
     */
    protected $schools;

    public function __construct()
    {
        $this->semesterTeachers = new ArrayCollection();
        $this->teacherHasReadingCertificates = new ArrayCollection();
        $this->schools = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\Teacher
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of user_id.
     *
     * @param integer $user_id
     * @return \Base\Entity\Teacher
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Get the value of user_id.
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Base\Entity\Teacher
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of edu_key.
     *
     * @param string $edu_key
     * @return \Base\Entity\Teacher
     */
    public function setEduKey($edu_key)
    {
        $this->edu_key = $edu_key;

        return $this;
    }

    /**
     * Get the value of edu_key.
     *
     * @return string
     */
    public function getEduKey()
    {
        return $this->edu_key;
    }

    /**
     * Set the value of gender.
     *
     * @param string $gender
     * @return \Base\Entity\Teacher
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get the value of gender.
     *
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set the value of last_update.
     *
     * @param \DateTime $last_update
     * @return \Base\Entity\Teacher
     */
    public function setLastUpdate($last_update)
    {
        $this->last_update = $last_update;

        return $this;
    }

    /**
     * Get the value of last_update.
     *
     * @return \DateTime
     */
    public function getLastUpdate()
    {
        return $this->last_update;
    }

    /**
     * Add SemesterTeacher entity to collection (one to many).
     *
     * @param \Base\Entity\SemesterTeacher $semesterTeacher
     * @return \Base\Entity\Teacher
     */
    public function addSemesterTeacher(SemesterTeacher $semesterTeacher)
    {
        $this->semesterTeachers[] = $semesterTeacher;

        return $this;
    }

    /**
     * Remove SemesterTeacher entity from collection (one to many).
     *
     * @param \Base\Entity\SemesterTeacher $semesterTeacher
     * @return \Base\Entity\Teacher
     */
    public function removeSemesterTeacher(SemesterTeacher $semesterTeacher)
    {
        $this->semesterTeachers->removeElement($semesterTeacher);

        return $this;
    }

    /**
     * Get SemesterTeacher entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSemesterTeachers()
    {
        return $this->semesterTeachers;
    }

    /**
     * Add TeacherHasReadingCertificate entity to collection (one to many).
     *
     * @param \Base\Entity\TeacherHasReadingCertificate $teacherHasReadingCertificate
     * @return \Base\Entity\Teacher
     */
    public function addTeacherHasReadingCertificate(TeacherHasReadingCertificate $teacherHasReadingCertificate)
    {
        $this->teacherHasReadingCertificates[] = $teacherHasReadingCertificate;

        return $this;
    }

    /**
     * Remove TeacherHasReadingCertificate entity from collection (one to many).
     *
     * @param \Base\Entity\TeacherHasReadingCertificate $teacherHasReadingCertificate
     * @return \Base\Entity\Teacher
     */
    public function removeTeacherHasReadingCertificate(TeacherHasReadingCertificate $teacherHasReadingCertificate)
    {
        $this->teacherHasReadingCertificates->removeElement($teacherHasReadingCertificate);

        return $this;
    }

    /**
     * Get TeacherHasReadingCertificate entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTeacherHasReadingCertificates()
    {
        return $this->teacherHasReadingCertificates;
    }

    /**
     * Set User entity (many to one).
     *
     * @param \Base\Entity\User $user
     * @return \Base\Entity\Teacher
     */
    public function setUser(User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get User entity (many to one).
     *
     * @return \Base\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Add School entity to collection.
     *
     * @param \Base\Entity\School $school
     * @return \Base\Entity\Teacher
     */
    public function addSchool(School $school)
    {
        $this->schools[] = $school;

        return $this;
    }

    /**
     * Remove School entity from collection.
     *
     * @param \Base\Entity\School $school
     * @return \Base\Entity\Teacher
     */
    public function removeSchool(School $school)
    {
        $this->schools->removeElement($school);

        return $this;
    }

    /**
     * Get School entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSchools()
    {
        return $this->schools;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'user_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'name',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'edu_key',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'gender',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'last_update',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'user_id', 'name', 'edu_key', 'gender', 'last_update');
        $relationFields = array('user');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'user_id', 'name', 'edu_key', 'gender', 'last_update');
    }
}